[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1qkT5Eh9KHMuPKc_8NVkXP-JTUMCJKkMnysOoUnrlAH8/edit?gid=0#gid=0"

[connections.snowflake]
account = "MHFRLWY-DU88623"
user = "napateek"
password = "pC3grwdqnt"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "INVENTORY"
schema = "INVENTORYTRACKER"
